name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v5

    - name: Install and cache dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: >
          autoconf automake libtool xsltproc docbook-xsl libxpm-dev libx11-dev
          libxinerama-dev

    - name: Run autoreconf
      run: autoreconf --install

    - name: Configure
      run: ./configure

    - name: Make
      run: make

  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [14.2, 14.3, 15.0]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Disable man-db auto-update
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo rm -f /var/lib/man-db/auto-update

      - name: Install and cache vbox dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          execute_install_scripts: true
          packages: >
            zstd libvirt-daemon-system virt-manager qemu-kvm libosinfo-bin axel
            expect screen sshpass

      - name: Build on FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.version }}
          prepare: |
            pkg install -y autoconf automake gmake libX11 libXpm libXinerama \
              docbook-xsl libxslt
          run: |
            aclocal
            autoconf
            autoheader
            automake --add-missing
            ./configure
            gmake
