name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  new-version:
    name: Preview Version Bump
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    outputs:
      next-version: ${{ steps.next-version.outputs.version }}
      has-next-version: ${{ steps.next-version.outputs.hasNextVersion }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - id: next-version
        uses: thenativeweb/get-next-version@2.7.1

      - name: Show the next version
        run: |
          echo "Should bump version: ${{ steps.next-version.outputs.hasNextVersion }}"
          echo "Next version: ${{ steps.next-version.outputs.version }}"

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        xinerama: ["enabled", "disabled"]
        xpm: ["enabled", "disabled"]
        native_kde: ["enabled", "disabled"]
        trace_events: ["true", "false"]
        delay_embedding_confirmation: ["true", "false"]
        dump_window_information: ["true", "false"]
        exit_gracefully: ["true", "false"]
        debug: ["true", "false"]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v5

    - name: Install and cache dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: >
          xsltproc docbook-xsl libxpm-dev libx11-dev libxinerama-dev meson

    - name: Set up build directory
      run: >
        meson setup build
          -D xinerama=${{ matrix.xinerama }}
          -D xpm=${{ matrix.xpm }}
          -D native_kde=${{ matrix.native_kde }}
          -D trace_events=${{ matrix.trace_events }}
          -D delay_embedding_confirmation=${{ matrix.delay_embedding_confirmation }}
          -D dump_window_information=${{ matrix.dump_window_information }}
          -D exit_gracefully=${{ matrix.exit_gracefully }}
          -D debug=${{ matrix.debug }}

    - name: Build
      run: meson compile -C build

  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ["14.2", "14.3", "15.0"]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Disable man-db auto-update
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo rm -f /var/lib/man-db/auto-update

      - name: Install and cache vbox dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          execute_install_scripts: true
          packages: >
            zstd libvirt-daemon-system virt-manager qemu-kvm libosinfo-bin axel
            expect screen sshpass

      - name: Build on FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.version }}
          prepare: |
            pkg install -y meson libX11 libXpm libXinerama docbook-xsl libxslt
          run: |
            meson setup build
            meson compile -C build
