name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v5

    - name: Install and cache dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: >
          autoconf automake libtool xsltproc docbook-xsl libxpm-dev libx11-dev
          libxinerama-dev

    - name: Run autoreconf
      run: autoreconf --install

    - name: Configure
      run: ./configure

    - name: Make
      run: make
