name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v5

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool xsltproc docbook-xsl \
          libxpm-dev libx11-dev libxinerama-dev

    - name: Run autoreconf
      run: autoreconf --install

    - name: Configure
      run: ./configure

    - name: Make
      run: make
