name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: merge-to-master
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  new-version:
    name: Get New Version
    runs-on: ubuntu-latest

    outputs:
      next-version: ${{ steps.next-version.outputs.version }}
      has-next-version: ${{ steps.next-version.outputs.hasNextVersion }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - id: next-version
        uses: thenativeweb/get-next-version@2.7.1

      - name: Show the next version
        run: |
          echo "Should bump version: ${{ steps.next-version.outputs.hasNextVersion }}"
          echo "Next version: ${{ steps.next-version.outputs.version }}"

  create-release:
    name: Create
    runs-on: ubuntu-latest

    if: needs.new-version.outputs.has-next-version == 'true'
    needs: [new-version]

    steps:
      - uses: actions/checkout@v5

      - name: Build distribution tarball
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo rm -f /var/lib/man-db/auto-update
          sudo apt-get update
          sudo apt-get install -y \
            xsltproc docbook-xsl libxpm-dev libx11-dev libxinerama-dev

          pip install 'meson>=1.5.0'
          meson setup --buildtype release _build -D c_std=gnu2x
          meson dist -C _build

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.new-version.outputs.next-version }}
          generate_release_notes: true
          files: "_build/meson-dist/*"
